#ifndef NAVIGATIONITEMTYPEENUM_H
#define NAVIGATIONITEMTYPEENUM_H

enum NavigationItemTyPeEnum
{
    PAGE_TOP,
    PAGE_FILE_BASE_INFO,
    PAGE_DOS_HEADER,
    PAGE_NT_HEADERS,
    PAGE_FILE_HEADER,
    PAGE_OPTIONAL_HEADER,
    PAGE_DATA_DIRECTORIES,
    PAGE_SECTION_HEADERS,
    PAGE_EXPORT_DIRECTORY,
    PAGE_IMPORT_DIRECTORY,
    PAGE_RESOURCE_DIRECTORY,
    PAGE_EXCEPTION_DIRECTORY,
    PAGE_RELOCATION_DIRECTORY,
    PAGE_DEBUG_DIRECTORY,
    PAGE_ADDRESS_CONVERTER,
    PAGE_DEPENDENCY_WALKER,
    PAGE_HEX_EDITOR,
    PAGE_IDENTIFIER,
    PAGE_IMPORT_ADDRESS,
    PAGE_QUICK_DISASSEMBLER,
    PAGE_REBUILDER,
    PAGE_RESOURCE_EDITOR,
    PAGE_UPX_UTILITY
};

#endif // NAVIGATIONITEMTYPEENUM_H
